#!/bin/bash
printf "Disabling BD PROCHOT in LINUX\n\n"
printf "This script containing the commands to disable BD PROCHOT will be created and placed in a boot directory with administrator privileges\n\n"
while true; do
	read -rp "Do you want to continue? [y/N]: " yn
		case $yn in
			[Yy]* ) break;;
			[Nn]* ) exit;;
			* ) printf "Error: write only 'y' or 'n'\n";;
		esac
    done
if [ "$(id -u)" != 0 ]; then
	printf "This script requires administrator privileges\
	sudo "$0" "$@" "
	exit
fi
printf "Installation of necessary packages...\n\n"
printf "Which distribution do you want to install?\n\n"
printf "1. Arch Linux\n"
printf "2. Ubuntu e derivati\n"
printf "3. Fedora e derivati\n"
printf "4. CentOS\n\n"

while true; do
	read -rp "Choose an option [1/2/3/4]: " option
		case $option in
			1 ) sudo pacman -S msr-tools; break;;
			2 ) sudo apt-get install msr-tools; break;;
			3 ) sudo rpm-ostree install msr-tools; break;;
			4 ) sudo yum install msr-tools; break;;
			* ) printf "Error: only write a number between 1 and 4";;
		esac
    done

sudo nano /usr/local/bin/disable_bd_prochot.sh << EOL
#!/bin/bash; modprobe msr; rdmsr 0x1FC; wrmsr 0x1FC value
EOL

sudo chmod +x /usr/local/bin/disable_bd_prochot.sh

sudo nano /etc/systemd/system/disable_bd_prochot.service << EOF
[Unit] Description=Disable BD PROCHOT [Service] Type=oneshot ExecStart=/usr/local/bin/disable_bd_prochot.sh [Install] WantedBy=multi-user.target
EOF

sudo systemctl enable disable_bd_prochot.service

while true; do
	read -rp "Do you want to reboot the system? [y/N]: " yn
		case $yn in
			[Yy]* ) sudo reboot; break;;
			[Nn]* ) exit;;
			* ) printf "Error: only write 'y' or 'n'\n";;
esac
done
